apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: be-lb-policy
  namespace: default
spec:
  source:
    name: myapp
  destination:
    name: be
  loadBalancing:
    name: ROUND_ROBRIN

