---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: myapp-v1-path 
spec:
  precedence: 1
  destination:
    name: myapp
  match:
    request:
      headers:
        uri:
          exact: /version
  route:
  - labels:
      version: v1
    weight: 100
  - labels:
      version: v2
    weight: 0    
