---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: fe-v1-be-v2
spec:
  precedence: 1
  match:
    source:
      name: myapp
      labels:
        version: v1
  destination:
    name: be
  route:
  - labels:
      version: v2
    weight: 100
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: myapp-v1 
spec:
  precedence: 2
  destination:
    name: myapp  
  route:
  - labels:
      version: v1
    weight: 100
  - labels:
      version: v2
    weight: 0    
